# Информация о сайте
title: "Милана Мартынова"
baseURL: "https://lanawx.github.io/mysite/"
defaultContentLanguage: "ru"
languageCode: "ru-ru"

# Тема
theme: "academic"

# Параметры
params:
  color_theme: "default"
  font: "default"
  day_night: true

# Меню
menu:
  main:
    - name: "Главная"
      url: "/"
      weight: 1
    - name: "Посты"
      url: "/post/"
      weight: 2
