# Информация о сайте
baseURL: "https://lanawx.github.io/mysite/"
title: "Мой персональный сайт"
theme: "hugo-blox-builder"
defaultContentLanguage: "ru"
languageCode: "ru-ru"

# Выходные форматы
outputs:
  home: ["HTML"]
  page: ["HTML"]
  section: ["HTML"]
  taxonomy: ["HTML"]
  term: ["HTML"]

# Модули
module:
  imports: []
