main:
  - name: "Главная"
    url: "/"
    weight: 1
  - name: "Посты"
    url: "/post/"
    weight: 2
  - name: "Проекты"
    url: "/project/"
    weight: 3
  - name: "Контакты"
    url: "#contact"
    weight: 4
