# Внешний вид
theme: academic
font: default
day_night: true

# Интересы
interests:
  - лакорны
  - фанфики
  - юри
  - жой

# Образование
education:
  courses:
    - course: Компьютерные и информационные науки
      institution: РУДН
      year: 2026

# Социальные сети
social:
  - icon: github
    icon_pack: fab
    url: https://github.com/lanawx

# Email
email: milanamartynova531@gmail.com
